### ISSUE TITLE
Glint Color gets reset when restarting minecraft

### ISSUE THREAD

**Issue by Xyberspace** [Pepperoni-Jabroni/NoMorePurple#3]
In modmenu the color remains set, however it is not in effect until i use the command again

**Comment by Xyberspace** [comment]
after some testing it seems like modmenu is the problem

**Comment by Pepperoni-Jabroni** [comment]
Thanks for taking a deep dive! Will see what I can find.

**Comment by Pepperoni-Jabroni** [comment]
Thanks again for reporting! This is fixed in 1.0.1. Enjoy!
